[PHP]
; Maximum upload size
upload_max_filesize = 1024M
post_max_size = 1024M

; Maximum execution time
max_execution_time = 3600
max_input_time = 3600

; Memory limit
memory_limit = 512M

; Error reporting
display_errors = On
error_reporting = E_ALL

; MySQL settings
mysqli.default_socket = /var/run/mysqld/mysqld.sock

; Timezone
date.timezone = Asia/Ho_Chi_Minh
